### ISSUE TITLE
Display result in button (or OnError/OnSuccess), No infinite load.

### ISSUE THREAD

**Issue by NewDark90** [johannesjo/angular-promise-buttons#13]
Can we have a way of changing how the button looks when it completes with either an error or a success? 

I made a directive that works based on booleans, but I'm getting sick of it as well. It's not the best, but it functions OK. Source here for reference: [loading-button.ts.txt](https://github.com/johannesjo/angular-promise-buttons/files/217768/loading-button.ts.txt)

This is the behavior described:
[On Success](https://zippy.gfycat.com/InexperiencedMeagerJerboa.webm)
[On Error](https://zippy.gfycat.com/BraveBlackBagworm.webm)

After about 2 seconds (or another specified time) it will revert back to normal.

It would also be cool to be able to specify a parameterless function to call OnError or OnSuccess based on a definition from the config, so anything is truly possible.

Also, I don't know how reasonable this is, but having a way to fail out if too much time has elapsed would also be wonderful. 

I could probably write most of this code for you, so that is an option as well.

**Comment by johannesjo** [comment]
I like your suggestions! Thanks for submitting them. I'm quite busy at the moment, but would start to work on it in may, when I've a little more time on my hands. Meanwhile feel free to submit a PR.

**Comment by NewDark90** [comment]
I wrote this behavior and have it working in the example section. I think I broke your tests, but I'm not sure. New to the whole git/github thing. 
How do I commit a branch to your repo so I can add it as a pull request? Or is that not how I should be thinking of this?

**Comment by NewDark90** [comment]
Nevermind. Read your contribute section and totally figured it out.

**Comment by NewDark90** [comment]
Everything is there except for timing out on an infinite load. Seemed complicated to get to work.

**Comment by johannesjo** [comment]
It's better to do this in two separate pull requests anyway I would say :) Are the tests running? If so just submit the PR and I do a code review tomorrow. Thank you for your effort so far!

**Comment by NewDark90** [comment]
I'm fairly sure I killed the tests, but all the examples are working as intended. 
TDD is a totally new thing to me and I'm pretty sure I would do it wrong. :)

Thanks for looking it over!

**Comment by johannesjo** [comment]
Hey there. I made some minor changes and pushed everything into the NewDark90-Button_Messages branch (https://github.com/johannesjo/angular-promise-buttons/tree/NewDark90-Button_Messages). You can start using it from there (or of course specify your own fork via bower). I've got to say, that I'm not 100% decided yet, if I will include everything for the next release, as I there is a lot of complexity added and I personally would prefer things to be done slightly different. Also using the `then` callbacks instead of `finally` might lead to some issues, though I'm not 100% sure, as tets run fine for now.
The onError onSeccess handlers might be something I'd rather see be done outside of the directive via the promise or if it is to be included with directive be handled via the & attribute for the directive.
The html loaded on success and on error has wonky feel to it, and I wouldn't personally use it. For my personal use case a simple class would suffice. The html for success and error could than be hidden via css.

Thank you very much for your work! I hope this is not discouraging for you and you continue to contribute to open source. If there are more people asking for this functionality, I might reconsider.

**Comment by NewDark90** [comment]
Sure thing. Do whatever you feel is best for your library. :) 

You've solved my problem just by allowing me to see how you solved the bigger issue of a promise button without having to do a bunch of trial and error disovery. 

I don't mind having the contribution being a permanent fork if it ends up that way. I appreciate you looking it over and attempting to fit it into your base build. 

And hey! By all means if you think there's a smarter way of accomplishing the same thing, be my guest. :) I'm not so in love with that solution to realize it's a bit ugly and unweildy.

Again, Thank you for all that you've put into this!
